apiVersion: v1
kind: Secret
metadata:
  name: smartloan-secrets
  namespace: smartloan-ai
type: Opaque
stringData:
  OPENAI_API_KEY: "your_openai_api_key_here"
  MARIADB_ROOT_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "root"
  SECRET_KEY: "your_secret_key_here"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smartloan-config
  namespace: smartloan-ai
data:
  # Qdrant Database
  QDRANT_URL: "http://qdrant-service:6333"
  
  # Redis/Valkey Database
  REDIS_HOST: "valkey-service"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://valkey-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://valkey-service:6379/1"
  
  # MariaDB Database
  MYSQL_USER: "root"
  MYSQL_HOST: "mariadb-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "demo_bot"
  
  # XGBoost Model
  XGBOOST_MODEL_PATH: "/appllm/models/xgboost_model.pkl"
  
  # App Config
  DEBUG: "False"
  LOG_LEVEL: "INFO"
