apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-config
  namespace: smartloan-ai
data:
  config.toml: |
    [browser]
    gatherUsageStats = false
    
    [server]
    port = 8051
    address = "0.0.0.0"
    headless = true
    runOnSave = false
    enableCORS = false
    enableXsrfProtection = false
    
    [theme]
    primaryColor = "#FF6B6B"
    backgroundColor = "#FFFFFF"
    secondaryBackgroundColor = "#F0F2F6"
    textColor = "#262730"
    
    [logger]
    level = "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui-deployment
  namespace: smartloan-ai
  labels:
    app: chatbot-ui
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
        component: frontend
    spec:
      containers:
      - name: chatbot-ui
        image: smartloan-ai/chatbot-ui:latest
        ports:
        - containerPort: 8051
        env:
        - name: BACKEND_API_URL
          value: "http://idp-api-service:8081"
        - name: STREAMLIT_SERVER_PORT
          value: "8051"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8051
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8051
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: streamlit-config
          mountPath: /root/.streamlit
        - name: ui-logs
          mountPath: /usr/src/app/logs
      volumes:
      - name: streamlit-config
        configMap:
          name: streamlit-config
      - name: ui-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui-service
  namespace: smartloan-ai
  labels:
    app: chatbot-ui
    component: frontend
spec:
  selector:
    app: chatbot-ui
  ports:
  - name: http
    port: 8051
    targetPort: 8051
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ui-ingress
  namespace: smartloan-ai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "chatbot-ui-service"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
spec:
  ingressClassName: nginx
  rules:
  - host: chatbot.smartloan.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-ui-service
            port:
              number: 8051
