apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: smartloan-ai
data:
  production.yaml: |
    log_level: INFO
    service:
      grpc_port: 6334
      http_port: 6333
    storage:
      storage_path: /qdrant/storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  namespace: smartloan-ai
  labels:
    app: qdrant
    component: vectordb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
        component: vectordb
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
        - name: qdrant-config
          mountPath: /qdrant/config/production.yaml
          subPath: production.yaml
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6333
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
      - name: qdrant-config
        configMap:
          name: qdrant-config
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: smartloan-ai
  labels:
    app: qdrant
    component: vectordb
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
    protocol: TCP
  - name: grpc
    port: 6334
    targetPort: 6334
    protocol: TCP
  type: ClusterIP
