apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  namespace: smartloan-ai
  labels:
    app: valkey
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
        component: cache
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:bookworm
        ports:
        - containerPort: 6379
        args:
        - --save
        - "60"
        - "1"
        volumeMounts:
        - name: valkey-data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: valkey-data
        persistentVolumeClaim:
          claimName: valkey-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: smartloan-ai
  labels:
    app: valkey
    component: cache
spec:
  selector:
    app: valkey
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP
